# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/nlitz88/OneDrive - The Pennsylvania State University/Spring 2023/CMPEN 417/Labs/Lab 3/cmpen417lab3/lab3_part2/lab3_part2.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
# IP: The module: 'design_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nlitz88/OneDrive - The Pennsylvania State University/Spring 2023/CMPEN 417/Labs/Lab 3/cmpen417lab3/lab3_part2/lab3_part2.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/nlitz88/OneDrive - The Pennsylvania State University/Spring 2023/CMPEN 417/Labs/Lab 3/cmpen417lab3/lab3_part2/lab3_part2.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
# IP: The module: 'design_1_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nlitz88/OneDrive - The Pennsylvania State University/Spring 2023/CMPEN 417/Labs/Lab 3/cmpen417lab3/lab3_part2/lab3_part2.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
